### ISSUE TITLE
Editar configuração da peça

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#1]
## Descrição
Quando o usuário faz upload de um arquivo _CAD_,  é necessário que ele consiga editar as configuraçãos da peça.

Algumas configurações exigem que o usuário adicione arquivos a mais (e.g., desenho 2D). É necessário que o usuário faça upload de arquivo(s) quando estas configurações forem inseridas. Porém, isto só preciso quando se passa de um valor _NULL_ para um valor _NOT NULL_... Se já foi feito um upload de um arquivo e o usuário apenas muda o tipo de valor, não exigiremos um novo arquivo

## TODOs
* [x] editar quantidade de peças
* [x] editar material
* [x] editar tratamentos
    * [x] editar tratamento térmico
    * [x] editar tratamento superficial
    * [x] quando se trocar de tipo de material, verificar se existe tratamentos. Senão, setar os tratamentos para null
* [x] editar tolerância
* [x] editar acabamento
* [x] editar número de roscas
* [x] enviar _request_ com novas configurações
