### ISSUE TITLE
Upload de arquivos auxiliares

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#11]
## Descrição
Algumas configurações precisam de arquivos auxiliares (e.g., acabamento precisa do desenho 2d).
É necessário que o usuário consiga fazer upload

## TODOs
- [x] Caixa de upload no dialog de edição
- [x] Request para back-end
- [x] Mudar estado dos items para adicionar arquivo
- [x] Checar se arquivo auxiliar é necessário
- [x] Visiliar arquivos auxiliares da peça
