### ISSUE TITLE
Realizar pedido

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#3]
## Descrição
É necessário a criação de um _component_ para mostrar o total/resumo do carrinho (compilado de todas as peças). Também ser possível realizar o pedido com todas as peças configuradas.

Ao clicar em "Fazer pedido" (apenas um _placeholder_, texto pode mudar), temos que seguir o seguinte fluxo:
1. Se não estiver logado, pedir para realizar login/cadastro
2. Mostrar mais uma vez o compilado do pedido mais detalhado
3. Caso confirmado, mostrar tela de confirmação (com os textos necessários)

Depende da issue #4 

## TODOs
* [ ] _component_ do carrinho/cesta
    * [ ] resumo do pedido
    * [ ] botão de realizar pedido
* [ ] se não logado, abrir dialog para login/cadastro
* [ ] _component_ de confirmação
    * [ ] compilado do pedido
    * [ ] botão para confirmar pedido
    * [ ] textos se deu certo/errado
