### ISSUE TITLE
Refatoração da escolha de material

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#5]
## Descrição
Atualmente, para o usuário escolher uma material, ele segue o seguinte fluxo
1. Seleciona uma "Material"
2. A lista de "Tipos de de Material" (que é uma sub categoria de "Materiais") atualiza
3. Seleciona um "Tipo de Material" o que atualiza o material da peça
Este fluxo não o ideal pois pode gerar erros/confusões na seleção

É necessario alterar o _layout_ para visualizar/selecionar os materiais.

## TODOs
- [x] Mostrar todos os "materiais" e "tipo de materiais"
- [x] ? Com esse novo sistema, alterar seleção de tratamentos
- [x] ? fazer o _dialog_ de edição de configuração seja _fullscreen_
