### ISSUE TITLE
Adição/edição de configurações da peça

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#6]
## Descrição
Algumas configurações precisam de mais detalhes, como:
1. Roscas podem ser externas e internas. Também, é preciso adicionar uma _flag_ para o usuário informar se tem (ou não) roscas na peça
2. A "tolerância" não necessariamente é referente a toda a peça. Então, é necessário altera o texto de "Tolerância" para "Menor tolerância"

Nocas configurações:
1. Recartilhado
2. Gravação: que pode ser feita das seguintes maneiras
    1. Tipado
    2. Caneca elétrica ou pneumática
    3. Usinado em baixo relevo
    4. LASER

## TODOs
- [x] Alterar texto de tolerância
- [x] Alterar como roscas são configuradas
    - [x] _Flag_ ou _switch_ para informar se tem roscas ou não
    - [x] Número de roscas
- [x] Adicionar recartilhado (não altera preço)
- [x] Adicionar gravação
