### ISSUE TITLE
Revisão #1

### ISSUE THREAD

**Issue by davi-souza** [ddasouza/dsm_platform#7]
## Descrição
Revisão número 1 do design/layout feita pelo Célio

## TODOs
- [x] na edição das configurações
    - [x] não usar tabs. Ter todas as configurações na mesma visão
    - [x] usar select/autocomplete na seleção da configuração
- [x] Colocar botão de upload no final
